[tool.poetry]
name = "images-scraper"
version = "0.1.0"
description = ""
authors = ["heartmarshall <heartmarshall@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
